import type { Metadata } from "next";
import "./globals.css";

import { Alexandria } from "next/font/google";
import { I18nProvider } from "./providers/I18nProvider";
import ClientLayout from "./components/ClientLayout";

const alexandria = Alexandria({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "حرفة | Herfa",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html>
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </head>
      <body className={alexandria.className}>
        <I18nProvider>
          <ClientLayout>
            {children}
          </ClientLayout>
        </I18nProvider>
      </body>
    </html>
  );
}
