import type { Metadata } from "next";
import "./globals.css";

import { Alexandria } from "next/font/google";

const alexandria = Alexandria({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "حرفة | Herfa",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </head>
      <body className={alexandria.className}>{children}</body>
    </html>
  );
}
